# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"model_urls": "00_encoder.ipynb",
         "conv3x3": "00_encoder.ipynb",
         "conv1x1": "00_encoder.ipynb",
         "BasicBlock": "00_encoder.ipynb",
         "Bottleneck": "00_encoder.ipynb",
         "ResNetEncoder": "00_encoder.ipynb",
         "resnet18": "00_encoder.ipynb",
         "resnet34": "00_encoder.ipynb",
         "resnet50": "00_encoder.ipynb",
         "resnet101": "00_encoder.ipynb",
         "resnet152": "00_encoder.ipynb",
         "ConvLayer": "01_decoder.ipynb",
         "ConcatLayer": "01_decoder.ipynb",
         "LambdaLayer": "01_decoder.ipynb",
         "upconv2x2": "01_decoder.ipynb",
         "DecoderConnect": "01_decoder.ipynb",
         "load_camvid_dataset": "02_utils.ipynb",
         "display_segmentation": "02_utils.ipynb",
         "display_segmentation_from_file": "02_utils.ipynb",
         "CamvidDataset": "02_utils.ipynb",
         "DynamicUNet": "03_unet.ipynb",
         "DiceLoss": "04_opt.ipynb",
         "dice_similarity": "04_opt.ipynb"}

modules = ["encoder.py",
           "decoder.py",
           "utils.py",
           "unet.py",
           "opt.py"]

doc_url = "https://dthiagarajan.github.io/dynamic_unet/"

git_url = "https://github.com/dthiagarajan/dynamic_unet/tree/master/"


def custom_doc_links(name): return None
